version: "3"
services: 
  app:
    image: springbooot-app
    restart: always
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  mysql:
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports: 
     - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
